namespace :rabbitmq do
    desc "Setup routing"
    task :setup do
      require "bunny"
  
      conn = Bunny.new
      conn.start
  
      ch = conn.create_channel
  
      # get or create exchange
      x = ch.fanout("carros")
  
      # get or create queue (note the durable setting)
      queue = ch.queue("carros", durable: true)
  
      # bind queue to exchange
      queue.bind("carros")
  
      conn.close
    end
  end